### ISSUE TITLE
generation.py中调用函数prompt2conversation()参数缺少一个model_path

### ISSUE THREAD

**Issue by liano3** [HowieHwong/TrustLLM#20]
![image](https://github.com/HowieHwong/TrustLLM/assets/100564124/c6354a54-7554-49bc-bed2-31525caeb941)
![image](https://github.com/HowieHwong/TrustLLM/assets/100564124/ad3912cf-a0c2-4502-866d-bc4f9dad9e61)

**Comment by HowieHwong** [comment]
感谢您的反馈，我们已修复该bug
