### ISSUE TITLE
Wrong computation of metrics for implicit ethics

### ISSUE THREAD

**Issue by Nikis14** [HowieHwong/TrustLLM#23]
Hello, thank you for your amazing work!
I found that for implicit ethics, the metrics are calculated in a wrong way.

Specifically, it happens [here](https://github.com/HowieHwong/TrustLLM/blob/4341021d520038ae197810931c07974f9734f2ad/trustllm_pkg/trustllm/task/ethics.py#L302). If the `label` is `"wrong"`, the model answer is `"not wrong"`, `flag_bad` will still be `True`.

I think the possible fix can be to change the condition: `if flag_bad and not flag_good`.

**Comment by HowieHwong** [comment]
Hi,
 
Thanks for your careful reminder! We have fixed this error. 🥰
