### ISSUE TITLE
Data Format

### ISSUE THREAD

**Issue by lazyeden** [HowieHwong/TrustLLM#32]
I would like to ask if for the same dataset, when generated using different models, will the data be processed into different formats? For example, will llama use special characters such as <<SYS>>, [INST].

**Comment by HowieHwong** [comment]
Yes, it will be processed into different formats by the predefined templates in FastChat.

**Comment by redwyd** [comment]
> Yes, it will be processed into different formats by the predefined templates in FastChat.
I noticed that the prompt of the privacy_awareness_query dataset contains two roles: system and third party user. However, it seems that during the test, the prompt is directly used as the user input instead of enclosing the system part with <<SYS>><</SYS>>. Will this affect the final test results?

**Comment by redwyd** [comment]
> Yes, it will be processed into different formats by the predefined templates in FastChat.

I noticed that the prompt of the privacy_awareness_query dataset contains two roles: system and third party user. However, it seems that during the test, the prompt is directly used as the user input instead of enclosing the system part with <<sys>><</sys>>. Will this affect the final test results?

**Comment by redwyd** [comment]
> Yes, it will be processed into different formats by the predefined templates in FastChat.

I noticed that the prompt of the privacy_awareness_query dataset contains two roles: system and third party user. However, it seems that during the test, the prompt is directly used as the user input instead of enclosing the system part with <SYS></SYS>. Will this affect the final test results?

**Comment by lazyeden** [comment]
> Yes, it will be processed into different formats by the predefined templates in FastChat.

I noticed that the prompt of the privacy_awareness_query dataset contains two roles: system and third party user. However, it seems that during the test, the prompt is directly used as the user input instead of enclosing the system part with system token <system></system>. Will this affect the final test results?
