### ISSUE TITLE
Gold "answer" ID is not supposed to be 0 in the codah data set

### ISSUE THREAD

**Issue by jinz2014** [HowieHwong/TrustLLM#39]
For the CODAH dataset, since it is a multiple-choice question-answering task, we evaluate the
accuracy by measuring the exact match between the responses generated by LLMs and the provided gold
answers.

The ID of the gold answer is not supposed to be 0. The ID starts from 1. In the dataset (dataset/truthfulness/internal.json), the ID of certain gold answers is 0. 
@HowieHwong

**Comment by wang2226** [comment]
Hi @jinz2014,

Thank you for pointing out this issue. There was a typo in the prompt, and the index should have started from 0. We have corrected this typo and updated the internal.json file accordingly. Please refer to [dataset.zip](https://github.com/HowieHwong/TrustLLM/blob/main/dataset/dataset.zip) for the revised dataset.

**Comment by jinz2014** [comment]
Please take a look at the codes in trustllm/task/truthfulness.py for computing the metric. 

    def eval_internal_codah(self, data):

        for item in codah_data:
            response = item['res']
            prediction = re.findall(r"Answer: (\d+)", response)[0] if re.findall(r"Answer: (\d+)", response) else "0"

When the regular expression has no match, the prediction is 0.  The response of an LLM may be "trash", but the prediction is 0. 
 
Thanks

**Comment by wang2226** [comment]
Yes, the evaluation needs to be changed accordingly to reflect the changes. I have changed the default indicator to be -1. Thank you for the reminder!
