### ISSUE TITLE
Misleading default config documentation 

### ISSUE THREAD

**Issue by ic-768** [HowieHwong/TrustLLM#41]
[The evaluation page of the guide](https://howiehwong.github.io/TrustLLM/guides/evaluation.html#api-setting) states that to use azure, you have to set `config.azure_openai = True`, implying that it's `False` by default. [That is not the case](https://github.com/HowieHwong/TrustLLM/blob/9b7b5e67b62a054b3b3c5905a10cf428f2b253df/trustllm_pkg/trustllm/config.py#L20).

**Comment by wiqrug** [comment]
THATS SO TRUE, IM STRUGGLING 8 HOURS FOR THIS CONFIGURATION

**Comment by HowieHwong** [comment]
Hi,

Really sorry for that! We have fixed it 😭

**Comment by wiqrug** [comment]
Hi,

Thank you for the recent fix. I was also able to resolve the issue on my
end within my FastAPI project by setting config.azure_openai=False.

I have a few additional questions regarding configurations and general
usage of the framework. The reason for my inquiry is that I am working on
my diploma project, and the provided documentation does not go into
sufficient detail on these aspects. Would you be available to assist me
with these matters?

I appreciate your time and consideration.

**Comment by HowieHwong** [comment]
> Hi, Thank you for the recent fix. I was also able to resolve the issue on my end within my FastAPI project by setting config.azure_openai=False. I have a few additional questions regarding configurations and general usage of the framework. The reason for my inquiry is that I am working on my diploma project, and the provided documentation does not go into sufficient detail on these aspects. Would you be available to assist me with these matters? I appreciate your time and consideration.

Yes, if you have any questions, just tell us. Our team will provide help to you as soon as possible.

**Comment by pearlmary** [comment]
when using config.azure_openai=True for Autogpt evaluation using gpt4 or so, we are getting some content filtering error which filters the prompt to the autogpt evaluation. In that case what did you do?
